version: "3"

services:
    fancy-db:
        image: endrjuskr/fancy-db:latest
        environment:
            - DB_PASSWORD=
            - DB_USER=postgres
            - DB_URL=`jdbc:postgresql://fancy-db:5432/fancy`

    fancy-api:
        image: endrjuskr/fancy-api:latest
        ports:
            - "8080:8080"
        environment:
            - DB_PASSWORD=
            - DB_USER=postgres
            - DB_URL=jdbc:postgresql://fancy-db:5432/fancy