apiVersion: v1
kind: Pod
metadata:
  name: fancy-api
  labels:
    app: fancy-api
spec:
  containers:
  - name: fancy-api
    image: endrjuskr/fancy-api
    imagePullPolicy: Always
    env:
      - name: DB_USER
        value: postgres
      - name: DB_URL
        value: jdbc:postgresql://fancy-db-service:5432/fancy
      - name: DB_PASSWORD
        value: ''
  nodeSelector:
    app: api