apiVersion: v1
kind: Pod
metadata:
  name: fancy-db
  labels:
    app: fancy-db
spec:
  containers:
  - name: fancy-db
    image: endrjuskr/fancy-db
    imagePullPolicy: Always
  nodeSelector:
    app: db